#include <stdio.h>
#include <conio.h>
main()



{

	int a=2 , b=0 , c=2 , d=5;
	
	printf(" %d %d %d %d \n", a++ , ++b , c ,d );
	// BURADA SONUÇ 2 1 2 5 OLUR ÇÜNKÜ A YI ÖNCE KULLANIP SONRA ARTTIRIYORUZ VE HENÜZ KULLANDIK 
	// B Yİ ÖNCE ARTTIRIP SONRA KULLANDIK O YÜZDEN ARTTIRILMIŞ HALİNİ YAZDIK
	// C YE İŞLEM UYGULAMADIK
	// D YE İŞLEM UYGULAMADIK
	
	printf(" %d %d %d %d \n" , a , b , c++ , d++);
	// BURADA SONUÇ 3 1 2 5 OLUR ÇÜNKÜ
	// A YI ÜSTTE ÖNCE KULLAN SONRA ARTTIR DEMİŞTİK ŞİMDİ KULLANDIĞIMIZ İÇİN ARTIK ARTTIRABİLİRİZ
	// B Yİ ÜSTTE ZATEN ARTTIRMIŞTIK BURADA BİR İŞLEM YAPMIYORUZ
	// C Yİ ÖNCE KULLAN SONRA ARTTIR DEMİŞŞİZ AMA HENÜZ KULLANMADIK
	// D Yİ ÖNCE KULLAN SONRA ARTTIR DEMİŞİŞZ AMA HENÜZ KULLANMADIK
	
	printf(" %d %d %d %d \n" , a , b++ , c , ++d);
	// BURADA SONUÇ 4 1 3 7 OLUR ÇÜNKÜ
	// A YI ÖNCE ARTTIR SONRA KULLAN DEMİŞİZ BU YÜZDEN DİREKT ARTTIRIYORUZ
	// B Yİ ÖNCE KULLAN SONRA ARTTIR DEDİĞİMİZ İÇİN VE HENÜZ KULLANMADIĞIMIZ İÇİN AYNI KALIYOR
	// C YE BİR ÖNCEKİ YERDE ÖNCE KULLAN SONRA ARTTIR DİYİP ŞİMDİDE KULLANDIĞIMIZ İÇİN BİR ARTTIRDIK
	// D Yİ HEM ÜSTTE ÖNCE KULLAN SONRA BİR ARTTIR DEDİĞİMİZ VE BURADA KULLANDIĞIMIZ İÇİN HEM DE
	// BURADA ÖNCE ARTTIR DEDİĞİMİZ SONRA KULLAN DEDİĞİMİZ İÇİN İKİ ARTTIRDIK
}